DROP TABLE IF EXISTS posts;

CREATE TABLE "posts" (
    "id"    INTEGER NOT NULL,
    "user_id"    INTEGER NOT NULL,
    "created"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "location"    TEXT NOT NULL,
    "image_path"    TEXT NOT NULL,
    PRIMARY KEY("id" AUTOINCREMENT)
);

DROP TABLE IF EXISTS users;

CREATE TABLE "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
)