---
- name: Update db servers
  hosts: databases
  remote_user: root
  become: yes

  tasks:
    - name: Ensure PostgreSQL and psycopg2 are installed
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL is running and enabled
      ansible.builtin.systemd:
        name: postgresql
        state: started
        enabled: true

    - name: Create database
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present
      become_user: postgres

    - name: Create database user with password
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
      become_user: postgres

    - name: Grant ALL privileges on DB to user
      community.postgresql.postgresql_privs:
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        type: database
        privs: ALL
        state: present
      become_user: postgres

    - name: Set listen_addresses in postgresql.conf
      community.postgresql.postgresql_set:
        name: listen_addresses
        value: "{{ pg_listen_ip }}"
        immediate: false
      become_user: postgres
      notify: Restart PostgreSQL

    - name: Add pg_hba rule
      community.postgresql.postgresql_pg_hba:
        dest: "/etc/postgresql/16/main/pg_hba.conf"
        type: host
        database: all
        user: all
        address: "{{ pg_allowed_net }}"
        method: scram-sha-256
        state: present
      become_user: postgres
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.systemd:
        name: postgresql
        state: restarted
