---
- name: Update web servers
  hosts: localhost
  remote_user: vagrant
  become: yes
  tasks:
    - name: Ensure that nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Ensure Flask and Gunicorn are installed
      ansible.builtin.apt:
        name:
          - python3-flask
          - gunicorn
        state: present
        update_cache: yes

    - name: Deploy Nginx reverse proxy config
      ansible.builtin.template:
        src: flask.conf.j2
        dest: /etc/nginx/sites-enabled/flask.conf
        mode: "0644"
      notify: Reload nginx

    - name: Remove default site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
