---
- name: Update web servers
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Ensure that nginx is installed
      ansible.builtin.dnf:
        name: nginx
        state: present
        update_cache: yes
     
    - name: Ensure Nginx cache dir exists 
      ansible.builtin.file:
        path: /var/cache/nginx
        state: directory
        owner: nginx
        group: nginx
        mode: "0775"     

    - name: Ensure app user exists
      ansible.builtin.user:
        name: "{{ app_user }}"
        create_home: yes
        shell: /sbin/nologin  
   
    - name: Ensure uploads dir exists (mount point) and is writable
      ansible.builtin.file:
        path: /srv/uploads
        state: directory
        owner: "{{ app_user }}"
        group: ec2-user
        mode: "02775" 
  
    - name: Add app user to ec2 group
      ansible.builtin.user:
        name: "{{ app_user }}"
        groups: "ec2-user"
        append: yes    

    - name: Ensure python3 and packages are installed
      ansible.builtin.dnf:
        name:
          - python3-pip
          - python3-devel
          - gcc
          - make
          - postgresql-devel
        state: present
        update_cache: yes
        
    - name: Ensure app directory exists
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"
    
    - name: Create virtualenv
      ansible.builtin.command: python3 -m venv {{ app_dir }}/venv
      args:
        creates: "{{ app_dir }}/venv/bin/activate"
        
    - name: Remove default site
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

