---
- name: Push Consul config (SERVER) and restart service
  hosts: consul
  become: true

  tasks:
    - name: Ensure config and data directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: consul
        group: consul
      loop:
        - /etc/consul.d
        - /var/lib/consul
    
    - name: Drop /etc/consul.d/consul.hcl (SERVER)
      copy:
        dest: /etc/consul.d/consul.hcl
        owner: consul
        group: consul
        mode: "0640"
        content: |
          datacenter  = "my-dc-1"
          data_dir    = "/var/lib/consul"
          client_addr = "0.0.0.0"

          ui_config {
            enabled = true
          }

          bind_addr      = "0.0.0.0"
          advertise_addr = "10.0.2.10"

          server           = true
          bootstrap_expect = 1
      notify: Restart consul
    
    - name: Ensure consul service is enabled and running
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started
      
  handlers:
    - name: Restart consul
      service:
        name: consul
        state: restarted
        enabled: true