---
- name: Push Consul config (SERVER) and restart service
  hosts: consul
  become: true

  tasks:
    - name: Ensure config and data directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: consul
        group: consul
      loop:
        - /etc/consul.d
        - /var/lib/consul
    
    - name: Add consul config using jinja2
      ansible.builtin.template:
       src: ../consul/consul-server/consul.hcl.j2
       dest: /etc/consul.d/consul.hcl
       mode: "0644"
       force: true
      notify: Restart consul
    
    - name: Ensure consul service is enabled and running
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started

    - name: Install Prometheus server (with Consul SD)
      ansible.builtin.import_role:
        name: prometheus.prometheus.prometheus
      vars:
        prometheus_scrape_configs:
          - job_name: "consul"
            consul_sd_configs:
              - server: "localhost:8500"
                services: []

    - name: Install Grafana (datasource + basic dashboard)
      ansible.builtin.import_role:
        name: prometheus.prometheus.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: "{{grafana_admin_pass}}"
        grafana_datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://localhost:9090
            isDefault: true
        grafana_dashboards:
          - dashboard_id: 1860
            revision_id: 33
            datasource: Prometheus

  handlers:
    - name: Restart consul
      service:
        name: consul
        state: restarted
        enabled: true