---
- name: Push Consul config (SERVER) and restart service
  hosts: consul
  become: true

  tasks:
    - name: Ensure config and data directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0750"
        owner: consul
        group: consul
      loop:
        - /etc/consul.d
        - /var/lib/consul
    
    - name: Add consul config using jinja2
      ansible.builtin.template:
       src: ../consul/consul-server/consul.hcl.j2
       dest: /etc/consul.d/consul.hcl
       mode: "0644"
       force: true
      notify: Restart consul
    
    - name: Ensure consul service is enabled and running
      ansible.builtin.systemd:
        name: consul
        enabled: true
        state: started
      
  handlers:
    - name: Restart consul
      service:
        name: consul
        state: restarted
        enabled: true