---
- name: Update web servers
  hosts: server
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Ensure Nginx is running and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
     
    - name: Deploy http-level cache config
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/cache.conf.j2"
        dest: /etc/nginx/conf.d/cache.conf
        mode: "0644"
    
    - name: Checkout Flask app from private repo
      ansible.builtin.git:
        repo: "https://{{ github_token }}@github.com/DevOps-project-intership/BirdWatching-Flask.git"
        version: "main"
        dest: "{{ app_dir }}"
        force: yes
        accept_hostkey: yes
      become_user: "{{ app_user }}"  

    - name: Install Python deps into venv (as root)
      ansible.builtin.command: "{{ app_dir }}/venv/bin/pip install -r {{ app_dir }}/requirements.txt"
      args:
        chdir: "{{ app_dir }}"

    - name: Fix venv ownership
      ansible.builtin.file:
        path: "{{ app_dir }}/venv"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes          

    - name: Drop .env from template
      ansible.builtin.template:
        src: env.j2
        dest: "{{ app_env_file }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0600"

    - name: Install systemd unit from template
      ansible.builtin.template:
        src: flask.service.j2
        dest: /etc/systemd/system/flask.service
        mode: "0644"
      notify: Reload systemd

    - name: Run DB tables creation script
      ansible.builtin.command: "{{ app_dir }}/venv/bin/python3 {{ app_dir }}/Birdwatching/create_db_tables.py"
      args:
        chdir: "{{ app_dir }}"
      become_user: "{{ app_user }}" 

    - name: Enable & start Flask service
      ansible.builtin.systemd:
        name: flask
        enabled: true
        state: started

    - name: Deploy Nginx reverse proxy config
      ansible.builtin.template:
        src: flask.conf.j2
        dest: /etc/nginx/conf.d/flask.conf
        mode: "0644"
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true